from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field

# Kept byte-for-byte identical to the CHECK constraint in
# supabase/migrations/..._create_chat_schema.sql (messages.role). Two walls
# enforce the same set: Pydantic rejects a bad role at the API boundary with a
# clean 422, the DB CHECK is the backstop. Drift here would be a bug.
MessageRole = Literal["user", "assistant", "tool", "system"]

# Length caps live in Pydantic, not the DB (the TEXT columns are unbounded) — the
# backend is the trust boundary, so it bounds free-text input to limit resource
# use. A conversation title is short; message content is generous enough for a
# long assistant answer but still capped so a single turn cannot be unbounded.
_TITLE_MAX = 200
_CONTENT_MAX = 100_000


class ConversationCreate(BaseModel):
    """Fields a client may supply when opening a conversation. `user_id` is
    intentionally absent — it is taken from the caller's JWT in the router, never
    from the request body. `title` is usually left unset and auto-generated by
    the chat engine from the first user message."""

    title: str | None = Field(default=None, min_length=1, max_length=_TITLE_MAX)


class ConversationUpdate(BaseModel):
    """Partial update — currently only the title is client-mutable (e.g. a manual
    rename). Ownership, timestamps, and id are never client-set."""

    title: str | None = Field(default=None, min_length=1, max_length=_TITLE_MAX)


class ConversationResponse(BaseModel):
    """A conversation row as returned to the client."""

    id: UUID
    user_id: UUID
    title: str | None = None
    created_at: datetime
    updated_at: datetime


class ConversationListResponse(BaseModel):
    """A page of conversations plus the total count of rows matching the filter
    (before pagination), so the client can render page controls. Mirrors
    SubscriptionListResponse."""

    items: list["ConversationResponse"]
    total: int


class MessageCreate(BaseModel):
    """A message as constructed by the backend chat engine before persisting.
    Not a raw client body — user turns arrive through the chat endpoint and the
    engine builds these — but it is still validated so nothing unvalidated (from
    the model or a tool result) reaches the DB.

    `content` is optional: a tool-call-only assistant turn carries no text, and a
    `role='tool'` message pairs its output with the `tool_call_id` it answers.
    """

    role: MessageRole
    content: str | None = Field(default=None, max_length=_CONTENT_MAX)
    # Provider-normalized assistant tool-call requests; opaque JSON at this layer.
    tool_calls: list[dict[str, Any]] | None = None
    # Present on role='tool' messages: which assistant tool call this answers.
    tool_call_id: str | None = Field(default=None, max_length=256)
    # Validated chart/table payload from a later task; rendered through typed
    # components, never as raw HTML.
    structured_payload: dict[str, Any] | None = None


class MessageResponse(BaseModel):
    """A stored message as returned to the client (full history replay)."""

    id: UUID
    conversation_id: UUID
    user_id: UUID
    role: MessageRole
    content: str | None = None
    tool_calls: list[dict[str, Any]] | None = None
    tool_call_id: str | None = None
    structured_payload: dict[str, Any] | None = None
    created_at: datetime


class MessageListResponse(BaseModel):
    """A page of a conversation's messages in chronological order, plus the total
    count before pagination."""

    items: list["MessageResponse"]
    total: int
